Add browser code, vex red, vex blue themes
remy/mit-license pull request #1643
Opened 2023-02-10 14:15 UTC by Axorax

#### Before you create your license page

Hosting costs $7 a month. I need help, so please donate a few months to keep this service going.

I've already had support to run the domain until 2032, but the hosting needs help too.

**[Please donate and keep this project running](https://www.paypal.me/rem)**

2023-02-11 07:49 UTC, Cplus360 approved these changes
Nice

2023-02-12 13:26 UTC, Axorax commented
Hey! Can you merge the PR?

2023-02-13 00:30 UTC, Richienb requested changes

2023-02-13 00:30 UTC, Richienb commented on themes/vex-red.css
> +}
Extraneous

2023-02-13 00:30 UTC, Richienb commented on themes/vex-blue.css
> +}
Extraneous

2023-02-13 00:30 UTC, Richienb commented on themes/vex-blue.css
> +    margin-bottom: 2.5rem!important;
```suggestion
    margin-bottom: 2.5rem !important;
```

2023-02-13 00:30 UTC, Richienb commented on themes/vex-red.css
> +    margin-bottom: 2.5rem!important;
```suggestion
    margin-bottom: 2.5rem !important;
```

2023-02-13 00:30 UTC, Richienb commented on themes/browser-code.css
> +    font-size: 13px!important;
```suggestion
    font-size: 13px !important;
```

2023-02-14 10:39 UTC, merged